name: Daily Random Streak

permissions:
  contents: write

on:
  schedule:
    - cron: "30 18 * * *"   # Runs once every day
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "kprem20"
          git config --global user.email "kpremsharma2005@gmail.com"

      - name: Random Commits
        run: |
          # Random number of commits (1-20)
          COMMITS=$((1 + RANDOM % 20))

          messages=(
            "Update README"
            "Code cleanup"
            "Minor improvements"
            "Bug fixes"
            "Refactor project"
            "Documentation update"
            "Improve project"
            "Routine maintenance"
            "Small changes"
            "Optimize files"
          )

          echo "Making $COMMITS commits today..."

          for ((i=1; i<=COMMITS; i++))
          do
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Commit $i - $RANDOM" >> streak.txt

              git add streak.txt

              MSG=${messages[$RANDOM % ${#messages[@]}]}

              git commit -m "$MSG"

             

              # Wait randomly between 1 and 15 minutes
              DELAY=$((60 + RANDOM % 781))
              echo "Waiting $DELAY seconds..."
              sleep $DELAY
          done
          git push
