name: Daily Streak Commit

permissions:
  contents: write

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Daily Change
        run: |
          echo "Day $(date +%d-%m-%Y): Consistency maintained" >> streak.txt

      - name: Commit and Push
        run: |
          git config --global user.name "kprem20"
          git config --global user.email "kpremsharma2005@gmail.com"
          git add .
          git commit -m "Daily auto commit" || echo "No changes"
          git push
